token:
  expiration_time: 86400000
  secret: '{cipher}AYBB97wO2p7BbqXHNlMqbzABM0pLmEJjTiZvashHq0BximmNPWN51Cfe6T8JOTcJ7PA4KbYl7xSFF+vIY9Ky2HBJ5SHiuSrx1u0cDD7nDquA4c7O8tyvk+6n9n9FK2YwLsvXqrzkifzuZDTlUsmm8FU1z3LsdLx4zPrCx2as+jMB1D4bTY+jviqV2HCY0EWrAVUVjNTyk/s7R88i55UAHJsch11gwDWiHYyJ8o3S+8rZeuJXMXhTNduGwbzj+LYtGjUZpUeYSIEKWymkQssIKQAt5Pf9SiZ3DuRLcbC8/lVv3AOnfOTVudp3ktqDOwdK3XCe4wJ6uNZ0lKxoRozPmLaI4WKlb36I2PgMla8XWamX7sWEc6DSBen48nnoNFIn3E2jl03KqJ/eS8KwEN9hbXzZ7v/kViKeHIGlJAef9Ir5SKex+MBHhA1TqFZRTBdwPXAc/BhyLZJtVqICT6QJ7/KNTqeD1irwstLPiP2/eseBgdj/a9r+1b1GuX0jk0e6qppNAMoYmRenM9ouDBPZU8Wwtnq9mrLghwbZ6uafwB/rjSrJ3LhR2IOfQfUj7oUaRso='

gateway:
  ip: 172.18.0.5